### ISSUE TITLE
Create planning tool

### ISSUE THREAD

**Issue by kgish** [kgish/toolbox-app#13]
The platform should also contain a planning tool.

**Comment by kgish** [comment]
![screenshot-demo participation tools-2017-05-11-23-14-48](https://cloud.githubusercontent.com/assets/79195/25972355/00267c8e-36a0-11e7-93c3-a282de18134e.png)

**Comment by kgish** [comment]
![screenshot-demo participation tools-2017-05-11-23-15-19](https://cloud.githubusercontent.com/assets/79195/25972366/070d504a-36a0-11e7-89dd-e94d855144c1.png)

**Comment by ghost** [comment]
Looks good, interesting to thing about which tooling should run directly integrated in the dashboard and what needs to run separate?
