### ISSUE TITLE
Turn tools on and off / show or hide

### ISSUE THREAD

**Issue by ghost** [kgish/toolbox-app#2]
A certain client needs only a specific  tool set. It would be great if it is possible to show only a selection of tools.
![suite-prop2](https://cloud.githubusercontent.com/assets/11832800/25662043/5507645e-3013-11e7-9a8e-3eacf79fc62c.jpg)

**Comment by kgish** [comment]
Started.

**Comment by ghost** [comment]
Great photoshop kind of works but not great :-)

**Comment by ghost** [comment]
How can I show and hide tools for a specific customer?

**Comment by kgish** [comment]
Just edit the user and add tools from the selection box:

![image](https://cloud.githubusercontent.com/assets/79195/25706806/c991bc7e-30e1-11e7-9765-1a13cdd92bc8.png)
